/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.app.App
import org.example.app.Date

fun main(){
    println(App().greeting)
    val d = Date(29, 5, 2026)
    println(d)
}